import {
  questionInterface,
  recommendedInterface,
  feedbackInterface,
  announcementCard,
  profileNavLinkInterface,
  GradesTableProps,
  DataType,
  GradeCollapseProps,
  TeacherAssignmentCardProps,
  StudentAssignmentCardProps,
  contentNameHealthInterface,
  healthCardInterface,
  ParentInfoInterface,
  ChildrenData,
  TeachersData,
} from "./componentsInterface";

import {
  UserInterface,
  UserDataInterface,
  emailInterface,
  userDataInterface,
  userDataParentInterface,
  signUpDataInterface,
  userDetailsInterface,
  reportsInterface,
} from "./userInterface";

export {
  UserInterface,
  UserDataInterface,
  questionInterface,
  recommendedInterface,
  feedbackInterface,
  emailInterface,
  userDataInterface,
  userDataParentInterface,
  signUpDataInterface,
  announcementCard,
  userDetailsInterface,
  reportsInterface,
  profileNavLinkInterface,
  GradesTableProps,
  DataType,
  GradeCollapseProps,
  TeacherAssignmentCardProps,
  StudentAssignmentCardProps,
  contentNameHealthInterface,
  healthCardInterface,
  ParentInfoInterface,
  ChildrenData,
  TeachersData,
};
